### ISSUE TITLE
If repaying from supplied balance, the deposit is not required

### ISSUE THREAD

**Issue by evgenykuzyakov** [NearDeFi/burrow-cash#163] opened 2021-11-22 21:53 UTC
Let's say you supply 10000 nDAI and then burrow 1000 nDAI. When you trying to repay, it tried to deposit 1000nDAI back, but you already have at least 9000 nDAI supplied. This supplied balance should be enough to repay the full borrowed amount

**Comment by miaojiang** [comment] 2022-03-30 05:21
Seems to be duplicate of #203

**Closed** 2022-04-02 17:46 UTC
