### ISSUE TITLE
Deposit of NEAR issue

### ISSUE THREAD

**Issue by evgenykuzyakov** [NearDeFi/burrow-cash#221] opened 2022-01-14 01:42 UTC
The deposit UI of NEAR doesn't display the correct balance. It only displays the native account balance, but doesn't take into account the balance of `wrap.near` token. Ideally we should sum the two balances together and present it to a user.

Once user selects the amount, figure out whether some part of the amount has to be wrapped first before deposit.

**Comment by miaojiang** [comment] 2022-04-04 17:35
Closing. Duplicate of #228.

**Closed by miaojiang** 2022-04-04 17:35 UTC
Labels: Needs Scoping
